project 'MovieApp_final.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieApp_final' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp_final
pod 'AFNetworking', '~>3.0'
end
